# [dbo].[Authors]

In [0]:
USE [LibraryK204]
GO

In [0]:
/****** Object:  Table [dbo].[Authors]    Script Date: 24.09.2020 12:55:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Authors](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Names] [nvarchar](80) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Books]

In [0]:
/****** Object:  Table [dbo].[Books]    Script Date: 24.09.2020 12:55:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Books](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Namees] [nvarchar](100) NOT NULL,
	[PublishDate] [datetime] NOT NULL,
	[BookCount] [int] NULL,
	[AuthorssId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Faculty]

In [0]:
/****** Object:  Table [dbo].[Faculty]    Script Date: 24.09.2020 12:55:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Faculty](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Names] [nvarchar](80) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Students]

In [0]:
/****** Object:  Table [dbo].[Students]    Script Date: 24.09.2020 12:55:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Students](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) NOT NULL,
	[Phone] [int] NOT NULL,
	[Studentkey] [int] NULL,
	[FacultyId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Students_to_Books]

In [0]:
/****** Object:  Table [dbo].[Students_to_Books]    Script Date: 24.09.2020 12:55:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Students_to_Books](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[StudentId] [int] NULL,
	[BooksId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Authors]

In [0]:
SET IDENTITY_INSERT [dbo].[Authors] ON 
INSERT [dbo].[Authors] ([Id], [Names]) VALUES (1, N'Semed Vurgun')
INSERT [dbo].[Authors] ([Id], [Names]) VALUES (2, N'Resid Behbudov')
INSERT [dbo].[Authors] ([Id], [Names]) VALUES (3, N'Ramiz Rovsen')
INSERT [dbo].[Authors] ([Id], [Names]) VALUES (4, N'Ali Xeyyam')
INSERT [dbo].[Authors] ([Id], [Names]) VALUES (5, N'Nizami Gencevi')
SET IDENTITY_INSERT [dbo].[Authors] OFF
GO

# [FK__Books__AuthorssI__267ABA7A]

In [0]:
ALTER TABLE [dbo].[Books]  WITH CHECK ADD FOREIGN KEY([AuthorssId])
REFERENCES [dbo].[Authors] ([Id])
GO

# [FK__Students__Facult__2B3F6F97]

In [0]:
ALTER TABLE [dbo].[Students]  WITH CHECK ADD FOREIGN KEY([FacultyId])
REFERENCES [dbo].[Faculty] ([Id])
GO

# [FK__Students___Books__2F10007B]

In [0]:
ALTER TABLE [dbo].[Students_to_Books]  WITH CHECK ADD FOREIGN KEY([BooksId])
REFERENCES [dbo].[Books] ([Id])
GO

# [FK__Students___Stude__2E1BDC42]

In [0]:
ALTER TABLE [dbo].[Students_to_Books]  WITH CHECK ADD FOREIGN KEY([StudentId])
REFERENCES [dbo].[Students] ([Id])
GO